
title: Objectively Random Blog (Jaynes stan)
author: Dr. Nick Firoozye
description: A blog about quantitative finance, machine learning, and algorithmic trading,
with naive forays into philosophy, science and programming.
url: "https://firoozye.github.io"
github_username: firoozye

# Build settings
theme: minima
plugins:
  - jekyll-feed

# MathJax settings
mathjax: true

# Kramdown settings - prevent interference with math
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false
  input: GFM
  hard_wrap: false
  parse_block_html: true
